config/routes.rb
KatiesGrmApp::Application.routes.draw do

  get "deletes/destroy"

  resources :grm_pics

  resources :grm_vetappts

  resources :grm_stylists

  resources :grm_grappts

  resources :grm_dogs

  resources :grm_users

  match '/delete_dogs' => 'delete#delete_dogs'

end

app/models/grm_grappt.rb
class GrmGrappt < ActiveRecord::Base
  attr_accessible :gr_date, :gr_fdate, :gr_style
end

app/controllers/grm_grappts_controller.rb
class GrmGrapptsController < ApplicationController
  # GET /grm_grappts
  # GET /grm_grappts.json
  def index
    @grm_grappts = GrmGrappt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grm_grappts }
    end
  end

  # GET /grm_grappts/1
  # GET /grm_grappts/1.json
  def show
    @grm_grappt = GrmGrappt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grm_grappt }
    end
  end

  # GET /grm_grappts/new
  # GET /grm_grappts/new.json
  def new
    @grm_grappt = GrmGrappt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grm_grappt }
    end
  end

  # GET /grm_grappts/1/edit
  def edit
    @grm_grappt = GrmGrappt.find(params[:id])
  end

  # POST /grm_grappts
  # POST /grm_grappts.json
  def create
    @grm_grappt = GrmGrappt.new(params[:grm_grappt])

    respond_to do |format|
      if @grm_grappt.save
        format.html { redirect_to @grm_grappt, notice: 'Grooming appointment was successfully created.' }
        format.json { render json: @grm_grappt, status: :created, location: @grm_grappt }
      else
        format.html { render action: "new" }
        format.json { render json: @grm_grappt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grm_grappts/1
  # PUT /grm_grappts/1.json
  def update
    @grm_grappt = GrmGrappt.find(params[:id])

    respond_to do |format|
      if @grm_grappt.update_attributes(params[:grm_grappt])
        format.html { redirect_to @grm_grappt, notice: 'Grooming appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grm_grappt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grm_grappts/1
  # DELETE /grm_grappts/1.json
  def destroy
    @grm_grappt = GrmGrappt.find(params[:id])
    @grm_grappt.destroy

    respond_to do |format|
      format.html { redirect_to grm_grappts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/grm_grappts_helper.rb
module GrmGrapptsHelper
end

app/views/grm_grappts/_form.html.erb
<%= form_for(@grm_grappt) do |f| %>
  <% if @grm_grappt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grm_grappt.errors.count, "error") %> prohibited this grm_grappt from being saved:</h2>

      <ul>
      <% @grm_grappt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gr_date, 'Appointment Date' %><br />
    <%= f.text_field :gr_date %><br />
  </div>
  <div class="field">
    <%= f.label :gr_fdate, 'Next Appointment' %><br />
    <%= f.text_field :gr_fdate %><br />
  </div>
  <div class="field">
    <%= f.label :gr_style, 'Hair Style' %><br />
    <%= f.text_field :gr_style %><br />
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/grm_grappts/edit.html.erb
  <div data-role="header" data-position="fixed">
    <h1>Edit Appointment</h1>
  </div>

  <div data-role="content">
    <%= render 'form' %>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_grappts/index.html.erb
  <div data-role="header" data-position="fixed">
    <h1>View Appts</h1>
    <%= link_to "New", new_grm_grappt_path, "data-role" => "button", "data-icon" => "plus", "class" => "ui-btn-right" %>
  </div>

  <div data-role="content">
    <ul data-role="listview" data-split-icon="gear">
      <% @grm_grappts.each do |grm_grappt| %>
        <li>
          <%= link_to "#{grm_grappt.gr_date}", grm_grappt %>
          <%= link_to 'Edit', edit_grm_grappt_path(grm_grappt) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_grappts/new.html.erb
  <div data-role="header" data-position="fixed">
    <h1>New Appointment</h1>
  </div>

  <div data-role="content">
    <%= render 'form' %>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_grappts/show.html.erb
<p id="notice"><%= notice %></p>
  <div data-role="header" data-position="fixed">
    <!-- <a href="delete_grappts" data-role="button" data-rel="dialog" class="ui-btn-right" data-icon="delete" datatransition="pop">Delete</a> -->
    <%= button_to "Delete", @grm_grappt, :method => :delete, :class => 'ui-btn-right', "data-icon" => "delete", :onclick => "return confirm('Are you sure?')" %>
    <h1>View Appts</h1>
  </div>

  <div data-role="content">
    <ul data-role="listview">
      <li>
        <p>Appointment Date:</p>
        <%= @grm_grappt.gr_date %>
      </li>

      <li>
        <p>Next Appointment:</p>
        <%= @grm_grappt.gr_fdate %>
      </li>
 
      <li>
        <p>Style:</p>
        <%= @grm_grappt.gr_style %>
      </li>
    </ul>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>