config/routes.rb
KatiesGrmApp::Application.routes.draw do

  get "deletes/destroy"

  resources :grm_pics

  resources :grm_vetappts

  resources :grm_stylists

  resources :grm_grappts

  resources :grm_dogs

  resources :grm_users

  match '/delete_dogs' => 'delete#delete_dogs'

end

app/models/grm_vetappt.rb
class GrmVetappt < ActiveRecord::Base
  attr_accessible :vet_date, :vet_fdate, :vet_fname, :vet_lname, :vet_vacc
end

app/controllers/grm_vetappts_controller.rb
class GrmVetapptsController < ApplicationController
  # GET /grm_vetappts
  # GET /grm_vetappts.json
  def index
    @grm_vetappts = GrmVetappt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grm_vetappts }
    end
  end

  # GET /grm_vetappts/1
  # GET /grm_vetappts/1.json
  def show
    @grm_vetappt = GrmVetappt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grm_vetappt }
    end
  end

  # GET /grm_vetappts/new
  # GET /grm_vetappts/new.json
  def new
    @grm_vetappt = GrmVetappt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grm_vetappt }
    end
  end

  # GET /grm_vetappts/1/edit
  def edit
    @grm_vetappt = GrmVetappt.find(params[:id])
  end

  # POST /grm_vetappts
  # POST /grm_vetappts.json
  def create
    @grm_vetappt = GrmVetappt.new(params[:grm_vetappt])

    respond_to do |format|
      if @grm_vetappt.save
        format.html { redirect_to @grm_vetappt, notice: 'Vet appointment was successfully created.' }
        format.json { render json: @grm_vetappt, status: :created, location: @grm_vetappt }
      else
        format.html { render action: "new" }
        format.json { render json: @grm_vetappt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grm_vetappts/1
  # PUT /grm_vetappts/1.json
  def update
    @grm_vetappt = GrmVetappt.find(params[:id])

    respond_to do |format|
      if @grm_vetappt.update_attributes(params[:grm_vetappt])
        format.html { redirect_to @grm_vetappt, notice: 'Vet appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grm_vetappt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grm_vetappts/1
  # DELETE /grm_vetappts/1.json
  def destroy
    @grm_vetappt = GrmVetappt.find(params[:id])
    @grm_vetappt.destroy

    respond_to do |format|
      format.html { redirect_to grm_vetappts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/grm_vetappts_helper.rb
module GrmVetapptsHelper
end

app/views/grm_vetappts/_form.html.erb
<%= form_for(@grm_vetappt) do |f| %>
  <% if @grm_vetappt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grm_vetappt.errors.count, "error") %> prohibited this grm_vetappt from being saved:</h2>

      <ul>
      <% @grm_vetappt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vet_fname, 'First Name' %><br />
    <%= f.text_field :vet_fname %><br />
  </div>
  <div class="field">
    <%= f.label :vet_lname, 'Last Name' %><br />
    <%= f.text_field :vet_lname %><br />
  </div>
  <div class="field">
    <%= f.label :vet_date, 'Date' %><br />
    <%= f.text_field :vet_date %><br />
  </div>
  <div class="field">
    <%= f.label :vet_fdate, 'Next Appointment Date' %><br />
    <%= f.text_field :vet_fdate %><br />
  </div>
  <div class="field">
    <%= f.label :vet_vacc, 'Vaccinations Received' %><br />
    <%= f.text_field :vet_vacc %><br />
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/grm_vetappts/edit.html.erb
  <div data-role="header" data-position="fixed">
    <h1>Edit Appointment</h1>
  </div>

  <div data-role="content">
    <%= render 'form' %>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear">Settings</a></li>
       <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_vetappts/index.html.erb
  <div data-role="header" data-position="fixed">
    <h1>View Appts</h1>
      <%= link_to "New", new_grm_vetappt_path, "data-role" => "button", "data-icon" => "plus", "class" => "ui-btn-right" %>
  </div>

  <div data-role="content">
    <ul data-role="listview" data-split-icon="gear">
      <% @grm_vetappts.each do |grm_vetappt| %>
        <li>
          <%= link_to "#{grm_vetappt.vet_date}", grm_vetappt %>
          <%= link_to 'Edit', edit_grm_vetappt_path(grm_vetappt) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_vetappts/new.html.erb
  <div data-role="header" data-position="fixed">
      <img src="assets/test.png" width='100%' height='10%'>
  </div>

  <div data-role="content">
    <%= render 'form' %>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_vetappts/show.html.erb
<p id="notice"><%= notice %></p>
  <div data-role="header" data-position="fixed">
    <%= button_to "Delete", @grm_vetappt, :method => :delete, :class => 'ui-btn-right', "data-icon" => "delete", :onclick => "return confirm('Are you sure?')" %>
    <!-- <a href="delete_vetappts" data-role="button" data-rel="dialog" class="ui-btn-right" data-icon="delete" datatransition="pop">Delete</a> -->
    <h1>View Appts</h1>
  </div>

  <div data-role="content">
    <ul data-role="listview">
      <li>
        <p>Vet First Name:</p>
        <%= @grm_vetappt.vet_fname %>
      </li>

      <li>
        <p>Vet Last Name:</p>
        <%= @grm_vetappt.vet_lname %>
      </li>
 
      <li>
        <p>Date:</p>
        <%= @grm_vetappt.vet_date %>
      </li>
    
      <li>
        <p>Next Appointment Date:</p>
        <%= @grm_vetappt.vet_fdate %>
      </li>
    
      <li>
        <p>Vaccinations Received:</p>
        <%= @grm_vetappt.vet_vacc %>
      </li>
    </ul>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>