config/routes.rb
KatiesGrmApp::Application.routes.draw do

  get "deletes/destroy"

  resources :grm_pics

  resources :grm_vetappts

  resources :grm_stylists

  resources :grm_grappts

  resources :grm_dogs

  resources :grm_users

  match '/delete_dogs' => 'delete#delete_dogs'

end

app/models/grm_dog.rb
class GrmDog < ActiveRecord::Base
  attr_accessible :allergies, :breed, :name, :weight
end

app/controllers/grm_dogs_controller.rb
class GrmDogsController < ApplicationController
  # GET /grm_dogs
  # GET /grm_dogs.json
  def index
    @grm_dogs = GrmDog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grm_dogs }
    end
  end

  # GET /grm_dogs/1
  # GET /grm_dogs/1.json
  def show
    @grm_dog = GrmDog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grm_dog }
    end
  end

  # GET /grm_dogs/new
  # GET /grm_dogs/new.json
  def new
    @grm_dog = GrmDog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grm_dog }
    end
  end

  # GET /grm_dogs/1/edit
  def edit
    @grm_dog = GrmDog.find(params[:id])
  end

  # POST /grm_dogs
  # POST /grm_dogs.json
  def create
    @grm_dog = GrmDog.new(params[:grm_dog])

    respond_to do |format|
      if @grm_dog.save
        format.html { redirect_to @grm_dog, notice: 'Dog was succesfully created.' }
        format.json { render json: @grm_dog, status: :created, location: @grm_dog }
      else
        format.html { render action: "new" }
        format.json { render json: @grm_dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grm_dogs/1
  # PUT /grm_dogs/1.json
  def update
    @grm_dog = GrmDog.find(params[:id])

    respond_to do |format|
      if @grm_dog.update_attributes(params[:grm_dog])
        format.html { redirect_to @grm_dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grm_dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grm_dogs/1
  # DELETE /grm_dogs/1.json
  def destroy
    @grm_dog = GrmDog.find(params[:id])
    @grm_dog.destroy

    respond_to do |format|
      format.html { redirect_to grm_dogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/grm_dogs_helper.rb
module GrmDogsHelper
end

app/views/grm_dogs/_form.html.erb
<%= form_for(@grm_dog) do |f| %>
  <% if @grm_dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grm_dog.errors.count, "error") %> prohibited this grm_dog from being saved:</h2>

      <ul>
      <% @grm_dog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
  </div>
  <div class="field">
    <%= f.label :breed %><br />
    <%= f.text_field :breed %><br />
  </div>
  <div class="field">
    <%= f.label :allergies %><br />
    <%= f.text_field :allergies %><br />
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %><br />
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
 <% end %>

app/views/grm_dogs/edit.html.erb
  <div data-role="header" data-position="fixed">
    <h1>Edit Dog Information</h1>
  </div>

  <div data-role="content">
    <%= render 'form' %>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear" class="ui-btn-active">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_dogs/index.html.erb
  <div data-role="header" data-position="fixed">
    <h1>My Dog</h1>
      <%= link_to "New", new_grm_dog_path, "data-role" => "button", "data-icon" => "plus", "class" => "ui-btn-right" %>
  </div>

  <div data-role="content">
    <ul data-role="listview" data-split-icon="gear">
      <% @grm_dogs.each do |grm_dog| %>
        <li>
          <%= link_to "#{grm_dog.name}'s Information", grm_dog %>
          <%= link_to 'Edit', edit_grm_dog_path(grm_dog) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear" class="ui-btn-active">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>

 

app/views/grm_dogs/new.html.erb
  <div data-role="header" data-position="fixed">
    <h1>New Dog</h1>
  </div>

  <div data-role="content">
    <%= render 'form' %>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear" class="ui-btn-active">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_dogs/show.html.erb
  <p id="notice"><%= notice %></p>

  <div data-role="header" data-position="fixed">
    <!-- <a href="delete_dogs" data-role="button" data-rel="dialog" class="ui-btn-right" data-icon="delete" datatransition="pop">Delete</a> -->
    <%= button_to "Delete", @grm_dog, :method => :delete, :class => 'ui-btn-right', "data-icon" => "delete", :onclick => "return confirm('This will delete your pet.  Are you sure?')" %>
    <h1>View Info</h1>
  </div>

  <div data-role="content">
    <ul data-role="listview">
      <li>
        <p>Name: </p>
        <%= @grm_dog.name %>
      </li>
      <li>
        <p>Breed: </p>
        <%= @grm_dog.breed %>
      </li>
      <li>
        <p>Allergies: </p>
        <%= @grm_dog.allergies %>
       </li>
      <li>
        <p>Weight: </p>
        <%= @grm_dog.weight %>
      </li>
    </ul>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear" class="ui-btn-active">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>