config/routes.rb
KatiesGrmApp::Application.routes.draw do

  get "deletes/destroy"

  resources :grm_pics

  resources :grm_vetappts

  resources :grm_stylists

  resources :grm_grappts

  resources :grm_dogs

  resources :grm_users

  match '/delete_dogs' => 'delete#delete_dogs'

end

app/models/grm_stylist.rb
class GrmStylist < ActiveRecord::Base
  attr_accessible :styl_fname, :styl_lname, :styl_specialty
end

app/controllers/grm_stylists_controller.rb
class GrmStylistsController < ApplicationController
  # GET /grm_stylists
  # GET /grm_stylists.json
  def index
    @grm_stylists = GrmStylist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grm_stylists }
    end
  end

  # GET /grm_stylists/1
  # GET /grm_stylists/1.json
  def show
    @grm_stylist = GrmStylist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grm_stylist }
    end
  end

  # GET /grm_stylists/new
  # GET /grm_stylists/new.json
  def new
    @grm_stylist = GrmStylist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grm_stylist }
    end
  end

  # GET /grm_stylists/1/edit
  def edit
    @grm_stylist = GrmStylist.find(params[:id])
  end

  # POST /grm_stylists
  # POST /grm_stylists.json
  def create
    @grm_stylist = GrmStylist.new(params[:grm_stylist])

    respond_to do |format|
      if @grm_stylist.save
        format.html { redirect_to @grm_stylist, notice: 'Stylist was successfully created.' }
        format.json { render json: @grm_stylist, status: :created, location: @grm_stylist }
      else
        format.html { render action: "new" }
        format.json { render json: @grm_stylist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grm_stylists/1
  # PUT /grm_stylists/1.json
  def update
    @grm_stylist = GrmStylist.find(params[:id])

    respond_to do |format|
      if @grm_stylist.update_attributes(params[:grm_stylist])
        format.html { redirect_to @grm_stylist, notice: 'Stylist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grm_stylist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grm_stylists/1
  # DELETE /grm_stylists/1.json
  def destroy
    @grm_stylist = GrmStylist.find(params[:id])
    @grm_stylist.destroy

    respond_to do |format|
      format.html { redirect_to grm_stylists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/grm_stylists_helper.rb
module GrmStylistsHelper
end

app/views/grm_stylists/_form.html.erb
<%= form_for(@grm_stylist) do |f| %>
  <% if @grm_stylist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grm_stylist.errors.count, "error") %> prohibited this grm_stylist from being saved:</h2>

      <ul>
      <% @grm_stylist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :styl_fname, 'First Name' %><br />
    <%= f.text_field :styl_fname %><br />
  </div>
  <div class="field">
    <%= f.label :styl_lname, 'Last Name' %><br />
    <%= f.text_field :styl_lname %><br />
  </div>
  <div class="field">
    <%= f.label :styl_specialty, 'Specialty' %><br />
    <%= f.text_field :styl_specialty %><br />
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/grm_stylists/edit.html.erb
  <div data-role="header" data-position="fixed">
    <h1>Edit Stylist Info</h1>
  </div>

  <div data-role="content">
    <%= render 'form' %>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear" class="ui-btn-active">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_stylists/index.html.erb
  <div data-role="header" data-position="fixed">
    <h1>My Stylist  </h1>
    <%= link_to "New", new_grm_stylist_path, "data-role" => "button", "data-icon" => "plus", "class" => "ui-btn-right" %>
  </div>

  <div data-role="content">
    <ul data-role="listview" data-split-icon="gear">
      <% @grm_stylists.each do |grm_stylist| %>
        <li>
          <%= link_to "#{grm_stylist.styl_fname}'s Information", grm_stylist %>
          <%= link_to 'Edit', edit_grm_stylist_path(grm_stylist) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear" class="ui-btn-active">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_stylists/new.html.erb
  <div data-role="header" data-position="fixed">
    <h1>New Stylist</h1>
  </div>

  <div data-role="content">
    <%= render 'form' %>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear" class="ui-btn-active">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>

app/views/grm_stylists/show.html.erb
<p id="notice"><%= notice %></p>
  <div data-role="header" data-position="fixed">
    <!-- <a href="delete_stylists" data-role="button" data-rel="dialog" class="ui-btn-right" data-icon="delete" datatransition="pop">Delete</a> -->
    <%= button_to "Delete", @grm_stylist, :method => :delete, :class => 'ui-btn-right', "data-icon" => "delete", :onclick => "return confirm('Are you sure?')" %>
    <h1>Pet Stylist</h1>
  </div>

  <div data-role="content">
    <ul data-role="listview">
      <li>
        <p>First Name:</b>
        <%= @grm_stylist.styl_fname %>
      </li>

      <li>
        <p>Last Name:</b>
        <%= @grm_stylist.styl_lname %>
      </li>

      <li>
        <p>Specialty:</b>
        <%= @grm_stylist.styl_specialty %>
      </li>
    </ul>
  </div>

  <div data-role="footer" data-mini="true" data-position="fixed">
    <div data-role="navbar" data-theme="a" data-mini="true">
      <ul>
        <li><a href="../../index.html" data-icon="home">Home</a></li>
        <li><a href="grm_pic" data-icon="arrow-r">Take Pic</a></li>
        <li><a href="../../index.html#settings" data-icon="gear" class="ui-btn-active">Settings</a></li>
        <li><a href="../../index.html#about_us" data-icon="info">About Us</a></li>
      </ul>
    </div>
  </div>